"$schema" = 'https://starship.rs/config-schema.json'

format = """
$status\
$cmd_duration\
$directory\
$character"""

# ── OS icon ─────────────────────────────────────────────────────────────────
[os]
format = '[ $symbol ]($style)'
style   = "bold prev_fg inverted"
disabled = false

# ── Execution time ──────────────────────────────────────────────────────────
[cmd_duration]
format            = "[ $duration ]($style)"
style             = "bold prev_fg"
min_time          = 0       # show always
show_milliseconds = true

# ── Exit status ─────────────────────────────────────────────────────────────
[status]
format            = '[ $symbol ]($style)'
success_style   = "bold blue inverted"
failure_style   = "bold red inverted"
success_symbol    = ""
not_found_symbol  = ""
symbol            = ""
disabled          = false

# ── Directory (second line, agnoster-short max 3 dirs) ───────────────────────
[directory]
format = '[ $path ]($style)'
style   = "bold prev_fg inverted"
disabled = false
truncate_to_repo = false
truncation_length = 0

# ── Prompt character (third line) ────────────────────────────────────────────
[character]
format          = "[$symbol]($style) "
success_symbol  = "[](bold prev_fg)"
error_symbol    = "[](bold prev_fg)"

# SYMBOLS
[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
