# Change the default Omarchy look'n'feel

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    rounding = 8

    blur {
        enabled = yes
        size = 2
        passes = 1
        vibrancy = 0.1
    }

    active_opacity = 0.95
    inactive_opacity = 0.95
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    enabled = yes

    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1

    animation = workspaces, 1, 6, smoothIn, slide
    animation = windows, 1, 5, smoothIn, slide
    animation = windowsOut, 1, 4, smoothOut, slide
    animation = fade, 1, 4, smoothIn
    animation = fadeDim, 1, 4, smoothIn
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
scrolling {
    # See only one column per screen instead of two
    # column_width = 0.97
}
