[desktop_widgets]
enabled = true
schema_version = 2
widget_order = ["clock_main"]

[desktop_widgets.grid]
visible               = true
cell_size             = 16
major_interval        = 4

[desktop_widgets.widget.clock_main]
type     = "clock"
output   = "eDP-1"
cx       = 960.0
cy       = 540.0
box_width  = 0.0
box_height = 0.0
rotation = 0.0

[desktop_widgets.widget.clock_main.settings]
clock_style = "digital"
format = "{:%H:%M}"
color  = "on_surface"
shadow = true
center_text = false
circle = true
