color0 #4d4355
color1 #ffb4ab
color2 #dcb8ff
color3 #dcb8ff
color4 #ffaeda
color5 #dcb8ff
color6 #dcb8ff
color7 #eadfee
color8 #988ca1
color9 #ffb4ab
color10 #dcb8ff
color11 #dcb8ff
color12 #ffaeda
color13 #dcb8ff
color14 #dcb8ff
color15 #eadfee

cursor                #eadfee
cursor_text_color     #16111b
background            #16111b
foreground            #eadfee
selection_foreground  #cfc2d7
selection_background  #4d4355
active_border_color   #dcb8ff
inactive_border_color #4d4355
url_color             #dcb8ff

active_tab_foreground   #480082
active_tab_background   #dcb8ff
inactive_tab_foreground #cfc2d7
inactive_tab_background #4d4355
cursor_trail_color      #cfc2d7
